### ISSUE TITLE
(meta) chore: Check package locally 1/2

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#31]
## Critères de validation 

ETQ client je peux voir que ...

- [x] Le `devtools::test()`est en succès: #36
- [x] Les examples fonctionnent
<img width="738" alt="Screenshot 2023-01-18 at 10 48 33" src="https://user-images.githubusercontent.com/35060481/213138871-d5026ce1-3093-44e1-9d72-cbce92176674.png">
<img width="690" alt="Screenshot 2023-01-18 at 10 48 40" src="https://user-images.githubusercontent.com/35060481/213138883-14a86e90-66b0-47c4-8acb-43bb282a20be.png">

- [x] Toutes les fonctions doivent avoir soit `@noRd` soit un `@export`

<img width="596" alt="Screenshot 2023-01-18 at 11 16 49" src="https://user-images.githubusercontent.com/35060481/213145515-a0b1851f-7717-4b7c-831a-9ff28e78c585.png">

- [x] Check spelling est ok

<img width="588" alt="Screenshot 2023-01-18 at 11 29 54" src="https://user-images.githubusercontent.com/35060481/213148511-adf54453-9f11-4873-b31e-d0e5cfd27198.png">

## Comment technique ?

- [ ] Les fonctions sont exécutées en local:
```
# Prepare for CRAN ----

# _Check in interactive test-inflate for templates and Addins
pkgload::load_all()
devtools::test()
testthat::test_dir("tests/testthat/")

# Test no output generated in the user files

# Run examples in interactive mode too
devtools::run_examples()

# PR in progress on the content of these lines
local <- utils::fileSnapshot (".", timestamp = tempfile("timestamp"), md5sum = TRUE)
home <- utils::fileSnapshot ("~", timestamp = tempfile("timestamp"), md5sum = TRUE)

# run tests or whatever, then ...
devtools::test()
devtools::run_examples()
# vignettes
dircheck <- tempfile("check")
dir.create(dircheck)
rcmdcheck::rcmdcheck(check_dir = dircheck)
# browseURL(dircheck)

the_dir <- list.files(file.path(dircheck), pattern = ".Rcheck", full.names = TRUE)
# Same tests, no new files
all(list.files(file.path(the_dir, "tests", "testthat")) %in%
list.files(file.path(".", "tests", "testthat")))

devtools::build_vignettes()
devtools::clean_vignettes()

utils::changedFiles(local, md5sum = TRUE)
utils::changedFiles(home, md5sum = TRUE)


# Check package as CRAN
rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"))
# devtools::check(args = c("--no-manual", "--as-cran"))

# Check content
# remotes::install_github("ThinkR-open/checkhelper")
checkhelper::find_missing_tags() # Toutes les fonctions doivent avoir soit `@noRd` soit un `@export`
checkhelper::check_clean_userspace(pkg = ".")
checkhelper::check_as_cran()

# Check spelling
# usethis::use_spell_check()
spelling::spell_check_package()

# Check URL are correct
# remotes::install_github("r-lib/urlchecker")
urlchecker::url_check()
urlchecker::url_update()

# Upgrade version number
usethis::use_version(which = c("patch", "minor", "major", "dev")[2])
```

**Comment by ArthurData** [comment]
@VincentGuyader peux-tu valider ce ticket stp ?

**Comment by ArthurData** [comment]
Validé pendant la réunion du 18/01/2023
