### ISSUE TITLE
(meta) chore: Check package locally 2/2

### ISSUE THREAD

**Issue by ArthurData** [ThinkR-open/checkhelper#43]
## Critères de validation

- [ ] Check URL are correct
- [ ] check_as_cran doit renvoyer 0, 0, 0
- [ ] Check package as CRAN retourne 0, 0, 0
- [ ] Le package n'ajoute pas de fichier supplémentaire dans le home ou le working directory

**Comment by statnmap** [comment]
Je valide
